package com.bruce.foundation.admin.model.security;

public class AdminRoleResource {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role_resource.id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role_resource.role_id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    private Integer roleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role_resource.resource_id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    private Integer resourceId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role_resource.id
     * @return  the value of admin_role_resource.id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role_resource.id
     * @param id  the value for admin_role_resource.id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role_resource.role_id
     * @return  the value of admin_role_resource.role_id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role_resource.role_id
     * @param roleId  the value for admin_role_resource.role_id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role_resource.resource_id
     * @return  the value of admin_role_resource.resource_id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role_resource.resource_id
     * @param resourceId  the value for admin_role_resource.resource_id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
}