package com.bruce.foundation.admin.model.security;

import java.util.Date;

public class AdminRole {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role.id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role.role_name
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    private String roleName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role.status
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    private Short status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role.create_time
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role.update_time
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role.id
     * @return  the value of admin_role.id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role.id
     * @param id  the value for admin_role.id
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role.role_name
     * @return  the value of admin_role.role_name
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role.role_name
     * @param roleName  the value for admin_role.role_name
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role.status
     * @return  the value of admin_role.status
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role.status
     * @param status  the value for admin_role.status
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role.create_time
     * @return  the value of admin_role.create_time
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role.create_time
     * @param createTime  the value for admin_role.create_time
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role.update_time
     * @return  the value of admin_role.update_time
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role.update_time
     * @param updateTime  the value for admin_role.update_time
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    @Override
    public boolean equals(Object obj) {
    	if(this == obj){
            return true;
        }
        if(obj instanceof AdminRole){
        	AdminRole roleObj = (AdminRole)obj;
            if(this.id!=null && this.id.equals(roleObj.id)){
                return true;
            }
        }
        return false;
    }
}