package com.bruce.foundation.admin.model.security;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.code
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.parent_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.resource_name
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.url
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.url_target
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private String urlTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.nav_menu
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Short navMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.sort
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.remark
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.status
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.create_time
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_resource.update_time
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.id
     *
     * @return the value of admin_resource.id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.id
     *
     * @param id the value for admin_resource.id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.code
     *
     * @return the value of admin_resource.code
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.code
     *
     * @param code the value for admin_resource.code
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.parent_id
     *
     * @return the value of admin_resource.parent_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.parent_id
     *
     * @param parentId the value for admin_resource.parent_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.resource_name
     *
     * @return the value of admin_resource.resource_name
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.resource_name
     *
     * @param resourceName the value for admin_resource.resource_name
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.url
     *
     * @return the value of admin_resource.url
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.url
     *
     * @param url the value for admin_resource.url
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.url_target
     *
     * @return the value of admin_resource.url_target
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public String getUrlTarget() {
        return urlTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.url_target
     *
     * @param urlTarget the value for admin_resource.url_target
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setUrlTarget(String urlTarget) {
        this.urlTarget = urlTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.nav_menu
     *
     * @return the value of admin_resource.nav_menu
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Short getNavMenu() {
        return navMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.nav_menu
     *
     * @param navMenu the value for admin_resource.nav_menu
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setNavMenu(Short navMenu) {
        this.navMenu = navMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.sort
     *
     * @return the value of admin_resource.sort
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.sort
     *
     * @param sort the value for admin_resource.sort
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.remark
     *
     * @return the value of admin_resource.remark
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.remark
     *
     * @param remark the value for admin_resource.remark
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.status
     *
     * @return the value of admin_resource.status
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.status
     *
     * @param status the value for admin_resource.status
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.create_time
     *
     * @return the value of admin_resource.create_time
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.create_time
     *
     * @param createTime the value for admin_resource.create_time
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_resource.update_time
     *
     * @return the value of admin_resource.update_time
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_resource.update_time
     *
     * @param updateTime the value for admin_resource.update_time
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    
    /**
     * 为菜单资源增加子菜单 
     */
    private List<AdminResource> childResources = new ArrayList<AdminResource>();

    public List<AdminResource> getChildResources() {
        return childResources;
    }

    public void setChildResources(List<AdminResource> childResources) {
        this.childResources = childResources;
    }
     
    public void addChild(AdminResource childResource){
        this.childResources.add(childResource);
    } 
    
    @Override
    public boolean equals(Object obj){
    	if(this == obj){
            return true;
        }
        if(obj instanceof AdminResource){
        	AdminResource resourceObj = (AdminResource)obj;
            if(this.id!=null && this.id.equals(resourceObj.id)){
                return true;
            }
        }
        return false;
    }
}