package com.bruce.foundation.admin.model.security;

public class AdminUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.user_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.role_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.id
     *
     * @return the value of admin_user_role.id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.id
     *
     * @param id the value for admin_user_role.id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.user_id
     *
     * @return the value of admin_user_role.user_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.user_id
     *
     * @param userId the value for admin_user_role.user_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.role_id
     *
     * @return the value of admin_user_role.role_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.role_id
     *
     * @param roleId the value for admin_user_role.role_id
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}