package com.bruce.foundation.admin.mapper.security;

import com.bruce.foundation.admin.model.security.AdminRoleResource;
import com.bruce.foundation.admin.model.security.AdminRoleResourceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int countByExample(AdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int deleteByExample(AdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int insert(AdminRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int insertSelective(AdminRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    List<AdminRoleResource> selectByExample(AdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    AdminRoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int updateByExampleSelective(@Param("record") AdminRoleResource record, @Param("example") AdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int updateByExample(@Param("record") AdminRoleResource record, @Param("example") AdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int updateByPrimaryKeySelective(AdminRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int updateByPrimaryKey(AdminRoleResource record);
}