package com.bruce.foundation.admin.mapper.security;

import com.bruce.foundation.admin.model.security.AdminResource;
import com.bruce.foundation.admin.model.security.AdminResourceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int countByExample(AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int deleteByExample(AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int insert(AdminResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int insertSelective(AdminResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    List<AdminResource> selectByExample(AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    AdminResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int updateByExampleSelective(@Param("record") AdminResource record, @Param("example") AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int updateByExample(@Param("record") AdminResource record, @Param("example") AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int updateByPrimaryKeySelective(AdminResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_resource
     *
     * @mbggenerated Thu Jul 10 18:39:11 CST 2014
     */
    int updateByPrimaryKey(AdminResource record);
}