package com.bruce.baseAdmin.mapper.security;

import com.bruce.baseAdmin.model.security.AdminUserRole;
import com.bruce.baseAdmin.model.security.AdminUserRoleCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminUserRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int countByExample(AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int deleteByExample(AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int insert(AdminUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int insertSelective(AdminUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    List<AdminUserRole> selectByExample(AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    AdminUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int updateByExampleSelective(@Param("record") AdminUserRole record,
            @Param("example") AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int updateByExample(@Param("record") AdminUserRole record,
            @Param("example") AdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int updateByPrimaryKeySelective(AdminUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_user_role
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int updateByPrimaryKey(AdminUserRole record);
}