package com.bruce.baseAdmin.mapper.security;

import com.bruce.baseAdmin.model.security.AdminResource;
import com.bruce.baseAdmin.model.security.AdminResourceCriteria;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminResourceMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int countByExample(AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int deleteByExample(AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int insert(AdminResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int insertSelective(AdminResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    List<AdminResource> selectByExample(AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    AdminResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int updateByExampleSelective(@Param("record") AdminResource record,
            @Param("example") AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int updateByExample(@Param("record") AdminResource record,
            @Param("example") AdminResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int updateByPrimaryKeySelective(AdminResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table admin_resource
     * @mbggenerated  Wed Aug 07 10:02:03 CST 2013
     */
    int updateByPrimaryKey(AdminResource record);
}